# Generated by Django 6.0.7 on 2026-08-20 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actuflow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image_une',
            field=models.ImageField(blank=True, null=True, upload_to='articles/'),
        ),
        migrations.AlterField(
            model_name='article',
            name='statut',
            field=models.CharField(choices=[('Brouillon', 'Brouillon'), ('En attente', 'En attente'), ('Soumis', 'Soumis'), ('Publie', 'Publié'), ('Archive', 'Archivé')], default='Brouillon', max_length=50),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='photo_profil',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
    ]
